config/routes.rb
Rails.application.routes.draw do
  
  resources :dresses
  devise_for :users, path: '', path_names: {sign_in: 'login',
  																					sign_out: 'logout',
  																					sign_up: 'register'}
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  
  resources :appointments

  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
end

app/models/dress.rb
class Dress < ApplicationRecord
	extend FriendlyId
	has_many :dress_images
	accepts_nested_attributes_for :dress_images, 
																reject_if: lambda { |attrs| attrs['image'].blank? }
																
	friendly_id :name, use: :slugged
end

app/models/dress_image.rb
class DressImage < ApplicationRecord
  belongs_to :dress
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :set_page_defaults

	def set_page_defaults
		@page_title = 'Salon venčanica Snežana'
		@seo_keywords = 'vencanica salon vencanica vencanice svecane haljine venčanica salon venčanica venčanice svečane haljine'
	end

	def current_user
		super || OpenStruct.new(email: 'guest@example.com')		
	end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  def create
    @page_title = 'Salon venčanica Snežana | Zakaži termin'
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /appointments/1
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /appointments/1
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:name, 
                                          :email, 
                                          :phone, 
                                          :app_date, 
                                          :app_time, 
                                          :app_status)
    end
end

app/controllers/dresses_controller.rb
class DressesController < ApplicationController
	before_action :set_dress, only: [:show, :edit, :update, :destroy]

	def index
		@dresses = Dress.all
	end

	def show
	end

	def new
		@dress = Dress.new
		5.times { @dress.dress_images.build }
	end

	def create
		@dress = Dress.new(dress_params)

		respond_to do |format|
			if @dress.save
				format.html {redirect_to new_dress_path, notice: 'Nova haljina je snimljena'}
			else
				format.html { render :new }
			end
		end
	end

	def edit
	end

	def update
		respond_to do |format|
			if @dress.update(dress_params)
				format.html { redirect_to dresses_path, notice: 'Izmene su sacuvane.'}
			else
				format.html { render :edit }
			end
		end
	end

	def destroy
		@dress.destroy
		respond_to do |format|
			format.html { redirect_to dresses_path, notice: 'Haljina je obrisana.'}
		end
	end

	private
		def set_dress
			@dress = Dress.friendly.find(params[:id])
		end

		def dress_params
			params.require(:dress).permit(:name, 
																		:short_desc, 
																		:long_desc, 
																		:kwrds, 
																		:main_img, 
																		:main_img,
																		dress_images_attributes: [:image]
																		)
		end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  	@page_title = 'Salon venčanica Snežana | O nama'
  end

  def contact
  	@page_title = 'Salon venčanica Snežana | Kontakt'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/dresses_helper.rb
module DressesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/appointments/_form.html.erb
<%= form_with(model: appointment, local: true) do |form| %>
  <% if appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :app_date %>
    <%= form.date_select :app_date %>
  </div>

  <div class="field">
    <%= form.label :app_time %>
    <%= form.time_select :app_time %>
  </div>

  <div class="field">
    <%= form.label :app_status %>
    <%= form.number_field :app_status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Appointments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>App date</th>
      <th>App time</th>
      <th>App status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.name %></td>
        <td><%= appointment.email %></td>
        <td><%= appointment.phone %></td>
        <td><%= appointment.app_date %></td>
        <td><%= appointment.app_time %></td>
        <td><%= appointment.app_status %></td>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path %>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @appointment.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @appointment.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @appointment.phone %>
</p>

<p>
  <strong>App date:</strong>
  <%= @appointment.app_date %>
</p>

<p>
  <strong>App time:</strong>
  <%= @appointment.app_time %>
</p>

<p>
  <strong>App status:</strong>
  <%= @appointment.app_status %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>

app/views/dresses/edit.html.erb
<h1>Izmeni podatek o ovoj venčanici</h1>

<%= form_for(@dress) do |frm| %>
	<div class="field">
		<%= frm.label :name %>
		<%= frm.text_field :name %>
	</div>

	<div class="field">
		<%= frm.label :short_desc %>
		<%= frm.text_area :short_desc %>
	</div>

	<div class="field">
		<%= frm.label :long_desc %>
		<%= frm.text_area :long_desc %>
	</div>

	<div class="field">
		<%= frm.label :kwrds %>
		<%= frm.text_field :kwrds %>
	</div>

	<div class="field">
		<%= frm.label :main_img %>
		<%= frm.text_field :main_img %>
	</div>

	<div class="field">
		<%= frm.label :main_thumb %>
		<%= frm.text_field :main_thumb %>
	</div>

	<div class="actions">
		<%= frm.submit %>
	</div>
<% end %>

app/views/dresses/index.html.erb
<main role="main">
  <div class="album py-5 bg-light">
    <div class="container">
      <% if current_user.is_a?(User) %>
        <%= link_to "Unesi novu haljinu", new_dress_path %>
      <% end %>
      <div class="row">

          <% @dresses.each do |dress| %>
            <div class="col-md-4">
              <div class="card mb-4 shadow-sm">
                <p>
              		<%= link_to dress_path(dress.id) do %>
              			<%=  image_tag dress.main_thumb, class: "card-img-top" %>
              		<% end %>
              	</p>
              	<p class="card-text"><%= link_to dress.name, dress_path(dress.id), class: "card-text" %></p>
              </div>
            </div>
          <% end %>

      </div>
    </div>
  </div>
</main>

app/views/dresses/new.html.erb
<h1>Unesi novu venčanicu</h1>

<%= form_for(@dress) do |frm| %>
	<div class="field">
		<%= frm.label :name %>
		<%= frm.text_field :name %>
	</div>

	<div class="field">
		<%= frm.label :short_desc %>
		<%= frm.text_area :short_desc %>
	</div>

	<div class="field">
		<%= frm.label :long_desc %>
		<%= frm.text_area :long_desc %>
	</div>

	<div class="field">
		<%= frm.label :kwrds %>
		<%= frm.text_field :kwrds %>
	</div>

	<div class="field">
		<%= frm.label :main_img %>
		<%= frm.text_field :main_img %>
	</div>

	<div class="field">
		<%= frm.label :main_thumb %>
		<%= frm.text_field :main_thumb %>
	</div>

	<ul>
		<%= frm.fields_for :dress_images do |dressimg| %>
			<li>
				<%= dressimg.label :image %>
				<%= dressimg.text_field :image %>
			</li>
		<% end %>
	</ul>

	<div class="actions">
		<%= frm.submit %>
	</div>
<% end %>

app/views/dresses/show.html.erb
<main role="main">

	<div id="dresSlider" class="carousel slide" data-ride="carousel">

	  <!-- Indicators -->
	  <ul class="carousel-indicators">
			<% @dress.dress_images.each do |di| %>
	    	<li data-target="#dresSlider" data-slide-to=<%= "#{(di.id - 1) % @dress.dress_images.count}" %>></li>
			<% end %>
	  </ul>

	  <!-- The slideshow -->
	  <div class="carousel-inner carousel-container-custom">

			<% @dress.dress_images.each do |di| %>
				<div class="carousel-item active">
					<p><%= image_tag di.image %> </p>
				</div>
			<% end %>

	  </div>

	  <!-- Left and right controls -->
	  <a class="carousel-control-prev" href="#demo" data-slide="prev">
	    <span class="carousel-control-prev-icon"></span>
	  </a>
	  <a class="carousel-control-next" href="#demo" data-slide="next">
	    <span class="carousel-control-next-icon"></span>
	  </a>

	</div>

	<h1><%= @dress.name %></h1>

	<p>
		<% if current_user.is_a?(User) %>
			<%= link_to 'Izmeni', edit_dress_path(@dress.id) %>
			<%= link_to 'Obriši', dress_path(@dress.id), method: :delete, data: { confrim: 'Jeste li sigurni?' } %>
		<% end %>
	</p>


</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="keywords" content="<%= @seo_keywords %>" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="text-center backgroundGradient">

    <div class="cover-container d-flex h-100 p-3 mx-auto flex-column">

      <div id="background"></div>

      <nav class="navbar navbar-expand-md navbar-light fixed-top container d-flex justify-content-center shadow"

          <h3 class="navbar-brand text-dark">Venčanice Snežana</h3>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#thisNavbar"
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="thisNavbar">
            <div class="nav-item nav-link"><%= link_to "Početna", root_path, class: "text-muted" %></div>
            <div class="nav-link"><%= link_to "O nama", about_path, class: "text-muted" %></div>
            <div class="nav-link"><%= link_to "Kontakt", contact_path, class: "text-muted" %></div>
            <div class="nav-link"><%= link_to "Venčanice", dresses_path, class: "text-muted" %></div>
            <div class="nav-link"><%= link_to "Zakažite termin", new_appointment_path, class: "text-muted" %></div>
            <div class="nav-link">
              <% if current_user.is_a?(User) %>
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "text-muted" %>
              <% end %>
            </div>
          </div>

      </nav>


      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>

      <footer class="mastfoot">
        <div class="inner">
          <p class="app-footer">Salon venčanica Snežana 2018. Sva prava zadržana.</p>
        </div>
      </footer>

    </div>

  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<main role="main" class="inner cover">

  <h1 class="cover-heading">Venčanice Snežana</h1>
  <p class="lead">Salon venčanica Snežana ima dugu tradiciju proizvodnje i prodaje venčanica.</p>
  <p class="lead">
    <%= link_to "Pogledajte naše haljine", dresses_path, class: "btn btn-lg btn-info" %>
    <%= link_to "Zakažite termin", new_appointment_path, class: "btn btn-lg btn-secondary" %>
  </p>

</main>